//! Where a helper may be installed from, and who owns it.
//!
//! Classification looks only at the fully resolved path of the invoking
//! executable. Nothing here searches `PATH` or guesses install locations:
//! whatever gets recorded is later executed by launchd at every login.

use super::record::{InstallRecord, OwnerKind};
use crate::errors::MonitorAgentError;
use std::path::{Component, Path, PathBuf};

/// Bundle identifier of `Git-Same.app`.
pub const APP_BUNDLE_ID: &str = "com.zaai.git-same";
const FORMULA_NAME: &str = "git-same-cli";

/// A candidate helper source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HelperSource {
    pub owner_kind: OwnerKind,
    /// Stable app bundle or CLI installation path.
    pub owner_path: PathBuf,
    /// Stable path recorded for future updates.
    pub source_binary: PathBuf,
    /// File to copy right now. Differs from `source_binary` only while a
    /// cask installer runs from its staging directory.
    pub copy_from: PathBuf,
}

/// Resolves and classifies the running executable.
pub fn invoking_source() -> Result<HelperSource, MonitorAgentError> {
    let invoked = std::env::current_exe()
        .map_err(|e| MonitorAgentError::MissingSource(format!("current executable: {e}")))?;
    // `current_exe` may be a symlink (Homebrew links, ~/.cargo/bin aliases).
    let real = std::fs::canonicalize(&invoked).unwrap_or(invoked);
    Ok(classify(&real))
}

/// Classifies an already canonicalized executable path.
pub fn classify(real_path: &Path) -> HelperSource {
    if let Some(bundle) = enclosing_app_bundle(real_path) {
        let helper = bundle.join("Contents").join("Helpers").join("git-same");
        return HelperSource {
            owner_kind: OwnerKind::App,
            owner_path: bundle,
            source_binary: helper.clone(),
            copy_from: helper,
        };
    }
    let stable = homebrew_opt_path(real_path).unwrap_or_else(|| real_path.to_path_buf());
    HelperSource {
        owner_kind: OwnerKind::Cli,
        owner_path: stable.clone(),
        source_binary: stable,
        copy_from: real_path.to_path_buf(),
    }
}

/// Source for a cask installation: copy from the staged bundle, but record
/// the final app path Homebrew is about to move it to.
pub fn cask_source(staged_executable: &Path, final_app_path: &Path) -> HelperSource {
    HelperSource {
        owner_kind: OwnerKind::HomebrewCask,
        owner_path: final_app_path.to_path_buf(),
        source_binary: final_app_path
            .join("Contents")
            .join("Helpers")
            .join("git-same"),
        copy_from: staged_executable.to_path_buf(),
    }
}

/// The `Git-Same.app` containing `path`, verified through its `Info.plist`.
fn enclosing_app_bundle(path: &Path) -> Option<PathBuf> {
    path.ancestors()
        .filter(|ancestor| ancestor.extension().is_some_and(|ext| ext == "app"))
        .find(|bundle| {
            std::fs::read_to_string(bundle.join("Contents").join("Info.plist")).is_ok_and(|plist| {
                plist_bundle_identifier(&plist).as_deref() == Some(APP_BUNDLE_ID)
            })
        })
        .map(Path::to_path_buf)
}

/// Minimal scan for `CFBundleIdentifier`. The bundle's `Info.plist` is
/// generated by this repository and is always XML.
fn plist_bundle_identifier(plist: &str) -> Option<String> {
    let after_key = plist.split("<key>CFBundleIdentifier</key>").nth(1)?;
    let start = after_key.find("<string>")? + "<string>".len();
    let end = after_key[start..].find("</string>")? + start;
    Some(after_key[start..end].trim().to_string())
}

/// Maps `<prefix>/Cellar/git-same-cli/<version>/bin/git-same` to the stable
/// `<prefix>/opt/git-same-cli/bin/git-same`, which survives `brew upgrade`.
/// Returned only when it really resolves to `real_path`.
fn homebrew_opt_path(real_path: &Path) -> Option<PathBuf> {
    let components: Vec<Component> = real_path.components().collect();
    let cellar = components.iter().rposition(|c| c.as_os_str() == "Cellar")?;
    if components.get(cellar + 1)?.as_os_str() != FORMULA_NAME {
        return None;
    }
    let prefix: PathBuf = components[..cellar].iter().collect();
    // Skip "Cellar/<formula>/<version>".
    let inside_keg: PathBuf = components.get(cellar + 3..)?.iter().collect();
    let candidate = prefix.join("opt").join(FORMULA_NAME).join(inside_keg);
    (std::fs::canonicalize(&candidate).ok()? == real_path).then_some(candidate)
}

/// Returns `true` for executables inside a cargo target directory.
///
/// Dev builds live in disposable worktrees and change on every build; they
/// must never be installed automatically over a user's real helper.
pub fn is_dev_build(real_path: &Path) -> bool {
    real_path.ancestors().any(|dir| {
        dir.file_name().is_some_and(|name| name == "target")
            && (dir.join("CACHEDIR.TAG").exists() || dir.join(".rustc_info.json").exists())
    })
}

/// What to do with the helper, given who is asking.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Selection {
    /// The installation is intact and current.
    Keep,
    /// Install or update from this source.
    Install(HelperSource),
    /// Nothing usable is installed and the caller cannot provide a source.
    Unavailable(String),
}

/// Applies the source selection rules for a non-cask caller.
///
/// * `existing`: the current record; `helper_intact`: the helper file exists.
/// * `caller`: the invoking app or CLI, when it could be resolved.
/// * `allow_dev_source`: explicit commands may install a dev build; automatic
///   recovery may not.
pub fn select(
    existing: Option<&InstallRecord>,
    helper_intact: bool,
    caller: Option<&HelperSource>,
    allow_dev_source: bool,
    source_changed: impl Fn(&InstallRecord) -> bool,
) -> Selection {
    let usable = |source: &HelperSource| allow_dev_source || !is_dev_build(&source.copy_from);
    let caller_usable = caller.is_some_and(usable);

    if let Some(record) = existing {
        let recorded_source = recorded_as_source(record);
        // The recorded source gets the same dev-build test as the caller. It
        // was written by an explicit Start, which may point at a cargo
        // `target/` build; automatic recovery must not then reinstall and
        // restart the monitor after every rebuild.
        let recorded_usable = usable(&recorded_source) && recorded_source.copy_from.exists();

        // A standalone owner yields to the app's signed bundled helper.
        if let Some(caller) = caller {
            if record.owner_kind == OwnerKind::Cli && caller.owner_kind.is_app() && caller_usable {
                return Selection::Install(caller.clone());
            }
        }
        if helper_intact {
            // Update only from the owner's own source; a different caller
            // never replaces a healthy helper.
            if source_changed(record) && recorded_usable {
                return Selection::Install(recorded_source);
            }
            return Selection::Keep;
        }
        // Helper missing: repair from the recorded owner when possible.
        if recorded_usable {
            return Selection::Install(recorded_source);
        }
    }

    let Some(caller) = caller else {
        return Selection::Unavailable("the invoking executable is unknown".to_string());
    };
    if caller_usable {
        let mut source = caller.clone();
        // The same bundle the cask installed keeps its cask ownership.
        if let Some(record) = existing {
            if record.owner_kind == OwnerKind::HomebrewCask
                && record.owner_path == caller.owner_path
            {
                source.owner_kind = OwnerKind::HomebrewCask;
            }
        }
        Selection::Install(source)
    } else {
        Selection::Unavailable(dev_build_reason())
    }
}

fn recorded_as_source(record: &InstallRecord) -> HelperSource {
    HelperSource {
        owner_kind: record.owner_kind,
        owner_path: record.owner_path.clone(),
        source_binary: record.source_binary.clone(),
        copy_from: record.source_binary.clone(),
    }
}

fn dev_build_reason() -> String {
    "this is a development build; run 'gisa monitor --start' to install it deliberately".to_string()
}

#[cfg(test)]
#[path = "source_tests.rs"]
mod tests;
